# Ateneo cleaning checks (task 6)

Checks for the Ateneo cleaning code in `src/transform/` (rules H in notebook 01). The pipeline runs that code through `clean_backfill.py`. This notebook only tests it and shows the results.

In [1]:
%load_ext autoreload
%autoreload 2

import sys
from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path.cwd().parent
sys.path.insert(0, str(PROJECT_ROOT))
RAW = PROJECT_ROOT / "data" / "raw"
STAGING = PROJECT_ROOT / "data" / "staging"

ateneo = pd.read_parquet(RAW / "ateneo_politicians_raw.parquet")
print(ateneo.shape)

(207599, 10)

## 1. Text repair, scanning errors, and suffixes

In [2]:
from src.transform.normalize import fix_mojibake, fix_ocr_digits, split_suffix

for col in ["first_name", "last_name", "party", "municipality"]:
    values = ateneo[col].dropna()
    print(col, "| values repaired:", (values.map(fix_mojibake) != values).sum())

towns = ateneo["municipality"].dropna().drop_duplicates()
repaired = towns.map(fix_mojibake)
pd.DataFrame({"before": towns, "after": repaired})[repaired != towns].head()

first_name | values repaired: 0
last_name | values repaired: 0
party | values repaired: 31
municipality | values repaired: 363

                  before              after
1255  SOFRONIO ESPAÃ‘OLA  SOFRONIO ESPAÑOLA
3668             DUEÃ‘AS             DUEÑAS
7190  SERGIO OSMEÃ‘A SR.  SERGIO OSMEÑA SR.
7192          LOS BAÃ‘OS          LOS BAÑOS
8757          PARAÃ‘AQUE          PARAÑAQUE

In [3]:
for name in ["CARIN0", "FILOMEN0", "DOM1NADOR", "PLARIDEL 1V", "ALAN1", "VICTOR 10"]:
    print(f"{name:12} -> {fix_ocr_digits(name)}")

CARIN0       -> CARINO
FILOMEN0     -> FILOMENO
DOM1NADOR    -> DOMINADOR
PLARIDEL 1V  -> PLARIDEL IV
ALAN1        -> ALAN1
VICTOR 10    -> VICTOR 10

In [4]:
examples = ["JOSE JR.", "SALICJR.", "ADOLFOJR", "GREGORIO 111", "REYNOLD JR. II", "SERGIO ANTONIO V", "NASR", "LEVI"]
pd.DataFrame({
    "name": examples,
    "split": [split_suffix(n) for n in examples],
    "split, 2019 rule": [split_suffix(n, glued_ok=True) for n in examples],
})

               name                     split          split, 2019 rule
0          JOSE JR.               (JOSE, Jr.)               (JOSE, Jr.)
1          SALICJR.              (SALIC, Jr.)              (SALIC, Jr.)
2          ADOLFOJR          (ADOLFOJR, None)             (ADOLFO, Jr.)
3      GREGORIO 111           (GREGORIO, III)           (GREGORIO, III)
4    REYNOLD JR. II         (REYNOLD, Jr. II)         (REYNOLD, Jr. II)
5  SERGIO ANTONIO V  (SERGIO ANTONIO V, None)  (SERGIO ANTONIO V, None)
6              NASR              (NASR, None)              (NASR, None)
7              LEVI              (LEVI, None)              (LEVI, None)

### Summary: text repair, scanning errors, and suffixes

- **Broken text:** 363 municipality values and 31 party values had a broken enye ("PARAÃ‘AQUE"). `fix_mojibake` repairs all of them. Names had none.
- **Scanning errors:** a 0 next to a letter becomes O, and a 1 right before a letter becomes I (CARIN0 → CARINO, PLARIDEL 1V → PLARIDEL IV). Digits that are not clearly letters stay as they are (ALAN1, VICTOR 10). Those rows get the `name_suspect` flag later.
- **Suffixes:** `split_suffix` moves JR., SR., II, III and so on into their own value. This includes "111" (→ III) and suffixes stuck to the name with a period (SALICJR.). Suffixes stuck to the name without a period (ADOLFOJR) are split only in 2019, the year spaces were lost. A final V stays, because it may be a middle initial.

## 2. First cleaning run (before the town review)

In [5]:
from src.transform.clean_backfill import clean_ateneo_politicians, known_town_pairs
from src.transform.mappings import ATENEO_PROVINCE_MAP

memberships = pd.read_parquet(STAGING / "hf_memberships_clean.parquet")
winners = pd.read_parquet(STAGING / "openhalalan_winners_clean.parquet")
known = known_town_pairs(memberships, winners)
at = clean_ateneo_politicians(ateneo, known)

print(at.shape, "| known towns:", len(known))
print("town_source:", at["town_source"].value_counts().to_dict())
print("town_verified:", at["town_verified"].value_counts(dropna=False).to_dict())

(207599, 24) | known towns: 1692
town_source: {'original': 172376, 'unfilled': 22032, 'not_applicable': 13191}
town_verified: {True: 170865, nan: 35223, False: 1511}

In [6]:
moved = at["province_std"] != at["province"].replace(ATENEO_PROVINCE_MAP)
print("rows moved to the right NCR district:", moved.sum())
at[moved].groupby(["year", "province", "town_std", "province_std"]).size()

rows moved to the right NCR district: 58

year  province               town_std  province_std
1988  NCR - FOURTH DISTRICT  PASIG     NCR SECOND DISTRICT    14
1992  NCR - FOURTH DISTRICT  PASIG     NCR SECOND DISTRICT    14
      NCR - THIRD DISTRICT   SAN JUAN  NCR SECOND DISTRICT     1
1995  NCR - SECOND DISTRICT  NAVOTAS   NCR THIRD DISTRICT      1
      NCR - THIRD DISTRICT   SAN JUAN  NCR SECOND DISTRICT     1
1998  NCR - FOURTH DISTRICT  PASIG     NCR SECOND DISTRICT    14
      NCR - THIRD DISTRICT   SAN JUAN  NCR SECOND DISTRICT     1
2019  NCR - THIRD DISTRICT   PATEROS   NCR FOURTH DISTRICT    12
dtype: int64

In [7]:
print("suffixes:", at["name_suffix"].value_counts().to_dict())
print("scanning errors:", at["name_suspect"].sum(), "| duplicate rows:", at["is_duplicate"].sum(), "| fat dynasty rows:", at["is_fat_dynasty"].sum())
at.loc[at["year"].eq(2019) & at["name_suffix"].notna(), ["first_name", "first_name_std", "name_suffix"]].head()

suffixes: {'Jr.': 2350, 'Sr.': 414, 'III': 223, 'II': 144, 'IV': 40, 'VI': 9, 'VII': 1, 'Jr. II': 1, 'Jr. IV': 1, 'VIII': 1}
scanning errors: 91 | duplicate rows: 13 | fat dynasty rows: 52932

       first_name first_name_std name_suffix
171819   ABBASJR.          ABBAS         Jr.
171866   JAIMESR.          JAIME         Sr.
171913    LACSJR.           LACS         Jr.
171936    AMERJR.           AMER         Jr.
172133   SALICJR.          SALIC         Jr.

In [8]:
unverified = at[at["town_verified"].eq(False)]
print(unverified["town_std"].nunique(), "town names in", len(unverified), "rows are not in HF or OpenHalalan")
unverified["year"].value_counts().sort_index()

114 town names in 1511 rows are not in HF or OpenHalalan

year
1988    776
1992    228
1995    166
1998    341
Name: count, dtype: int64

### Summary: first cleaning run

- **Rows:** all 207,599 rows are kept, with 14 new columns (row id, standard places, name parts, and flags).
- **Towns:** 172,376 town-level rows have a town. 22,032 have none: 15,842 in 2013 and 6,180 in 2016 (the gaps HF already filled, which section 5 copies over), plus 10 rows in 1988 written "---". The other 13,191 rows are provincial or House positions, which have no town.
- **NCR districts:** 58 rows filed under the wrong Metro Manila district moved to their city's district.
- **Names:** 3,184 suffixes moved to `name_suffix`, 91 names with scanning errors flagged, and 13 duplicate rows flagged.
- **Unknown towns:** 1,511 rows (114 names, all from 1988 to 1998) use a town name that neither HF nor OpenHalalan has. Section 3 reviews them.

## 3. Town name review

A town name counts as verified when HF or OpenHalalan records the same town in the same province group. For each unknown name, `suggest_town_fixes` gives two clues: a known town of the same province with almost the same spelling, and the known town where most of the same surnames held office within the next 10 years. We accept a suggestion when it makes sense, and write down the reason whenever we decide differently. HF's spelling stays the standard, so existing outputs keep their names.

### 3a. OpenHalalan names that HF never uses

In [10]:
from src.transform.mappings import PROVINCE_GROUP
from src.transform.normalize import name_key
from src.utils.town_review import suggest_town_fixes

persons = pd.read_parquet(STAGING / "hf_persons_clean.parquet")
town_positions = ["MAYOR", "VICE MAYOR", "COUNCILOR"]

hf = memberships[memberships["position"].isin(town_positions) & memberships["locality_source"].eq("original")]
hf = hf.merge(persons[["id", "last_key"]], left_on="person_id", right_on="id")
hf = hf.rename(columns={"locality_std": "town_std"})
hf["province_group"] = hf["province_std"].replace(PROVINCE_GROUP)

oh = winners[winners["position"].isin(town_positions) & ~winners["town_shift_suspect"] & winners["town_std"].notna()].copy()
oh["province_group"] = oh["province_std"].replace(PROVINCE_GROUP)
oh["last_key"] = oh["last_name"].map(name_key, na_action="ignore")

hf_towns = set(zip(hf["province_group"], hf["town_std"]))
oh_only = oh[[pair not in hf_towns for pair in zip(oh["province_group"], oh["town_std"])]]
review_oh = suggest_town_fixes(oh_only, hf)
print(len(review_oh), "OpenHalalan town names that HF never uses, in", review_oh["rows"].sum(), "rows")
review_oh

The history saving thread hit an unexpected error (OperationalError('database or disk is full')).History will not be written to the database.
56 OpenHalalan town names that HF never uses, in 1372 rows

,province_group,town_std,rows,years,spelling,shared_town,shared,of,suggestion
0,ABRA,SAL LAPADAN,10,[2001],SALLAPADAN,SALLAPADAN,6,10,SALLAPADAN
1,BATANGAS,MATAASNAKAHOY,10,[2025],MATAAS NA KAHOY,NaN,0,10,MATAAS NA KAHOY
2,BATANGAS,STO TOMAS,20,"[2022, 2025]",SANTO TOMAS,NaN,0,10,SANTO TOMAS
3,BENGUET,LA TRINIDAD CAPITAL,19,"[2004, 2007]",NaN,LA TRINIDAD,9,9,LA TRINIDAD
4,BOHOL,GETAFE,20,"[2022, 2025]",JETAFE,NaN,0,9,JETAFE
5,BULACAN,BALIWAG,10,[2025],BALIUAG,NaN,0,8,BALIUAG
6,CEBU,PINAMUNGAJAN,30,"[2001, 2022, 2025]",PINAMUNGAHAN,PINAMUNGAHAN,9,10,PINAMUNGAHAN
7,COTABATO,KADAYANGAN,10,[2025],NaN,NaN,0,10,NaN
8,COTABATO,KAPALAWAN,10,[2025],NaN,NaN,0,10,NaN
9,COTABATO,LIGAWASAN,10,[2025],NaN,NaN,0,9,NaN
10,COTABATO,M LANG,29,"[2001, 2004, 2007]",MLANG,MLANG,7,10,MLANG
11,COTABATO,MALIDEGAO,10,[2025],NaN,NaN,0,10,NaN
12,COTABATO,NABALAWAG,10,[2025],NaN,NaN,0,10,NaN
13,COTABATO,OLD KAABAKAN,10,[2025],NaN,NaN,0,10,NaN
14,COTABATO,PAHAMUDDIN,10,[2025],NaN,NaN,0,10,NaN
15,COTABATO,TUGUNAN,10,[2025],TULUNAN,NaN,0,9,TULUNAN
16,DAVAO ORIENTAL,BANAY BANAY,10,[2001],BANAYBANAY,BANAYBANAY,6,10,BANAYBANAY
17,EASTERN SAMAR,SAN POLICARPIO,10,[2001],SAN POLICARPO,SAN POLICARPO,5,8,SAN POLICARPO
18,IFUGAO,LAGAWE BURNAY,9,[2004],NaN,LAGAWE,9,9,LAGAWE
19,ILOCOS SUR,SALCEDO BAUGEN,60,"[2004, 2007, 2010, 2013, 2016, 2019]",NaN,SALCEDO,9,9,SALCEDO
20,ILOCOS SUR,SAN JUAN LAPOG,60,"[2004, 2007, 2010, 2013, 2016, 2019]",NaN,SAN JUAN,10,10,SAN JUAN
21,KALINGA,KABUGAO CAPITAL,20,"[2004, 2007]",NaN,KABUGAO,9,9,KABUGAO
22,LANAO DEL NORTE,S N DIMAPORO KAROMATAN,20,"[2004, 2007]",NaN,SULTAN NAGA DIMAPORO,10,10,SULTAN NAGA DIMAPORO
23,LANAO DEL NORTE,SULTAN NAGA DIMAPORO KAROMATAN,40,"[2010, 2013, 2016, 2019]",SULTAN NAGA DIMAPORO,SULTAN NAGA DIMAPORO,8,8,SULTAN NAGA DIMAPORO
24,LANAO DEL SUR,AMAI MANABILANG,20,"[2022, 2025]",NaN,NaN,0,8,NaN
25,LANAO DEL SUR,AMAI MANABILANG BUMBARAN,20,"[2016, 2019]",NaN,BUMBARAN,8,8,BUMBARAN
26,LANAO DEL SUR,BACOLOD KALAWI BACOLOD GRANDE,40,"[2004, 2010, 2016, 2019]",NaN,BACOLOD KALAWI,9,9,BACOLOD KALAWI
27,LANAO DEL SUR,MASUI,10,[2001],MASIU,MASIU,6,9,MASIU
28,LANAO DEL SUR,PAGAYAWAN TATARIKAN,46,"[2004, 2007, 2010, 2016, 2019]",NaN,PAGAYAWAN,7,7,PAGAYAWAN
29,LANAO DEL SUR,SULTAN GUMANDER,20,"[2001, 2004]",NaN,PICONG,6,10,PICONG
30,LEYTE,JAVIER BUGHO,56,"[2004, 2007, 2010, 2013, 2016, 2019]",NaN,JAVIER,8,8,JAVIER
31,LEYTE,TACLOBAN CITY CAPITAL,12,[2004],NaN,TACLOBAN,12,12,TACLOBAN
32,MAGUINDANAO,SHARIFF AGUAK CAPITAL,10,[2001],NaN,SHARIFF AGUAK,2,3,NaN
33,MASBATE,PIO V CORPUS,10,[2025],PIO V CORPUZ,NaN,0,10,PIO V CORPUZ
34,MISAMIS OCCIDENTAL,D V CHIONGBIAN D M MARCOS,18,"[2004, 2007]",NaN,DON VICTORIANO CHIONGBIAN,9,9,DON VICTORIANO CHIONGBIAN
35,MISAMIS OCCIDENTAL,DON V CHIONGBIAN,10,[2001],NaN,DON VICTORIANO CHIONGBIAN,5,10,DON VICTORIANO CHIONGBIAN
36,MOUNTAIN PROVINCE,PARACELIS PARACALES,10,[2004],NaN,PARACELIS,10,10,PARACELIS
37,NCR THIRD DISTRICT,KALOOCAN,27,"[2001, 2004]",KALOOKAN,KALOOKAN,10,14,KALOOKAN
38,NEGROS ORIENTAL,BAYAWAN CITY TULONG,44,"[2004, 2007, 2016, 2019]",NaN,BAYAWAN,11,11,BAYAWAN
39,NEGROS ORIENTAL,BINDOY PAYABON,40,"[2004, 2007, 2016, 2019]",NaN,BINDOY,10,10,BINDOY
40,NEGROS ORIENTAL,DUMAGUETE CITY CAPITAL,20,"[2004, 2007]",NaN,DUMAGUETE,10,10,DUMAGUETE
41,NUEVA ECIJA,GABALDON BITULOK & SABANI,20,"[2004, 2007]",NaN,GABALDON,10,10,GABALDON
42,NUEVA ECIJA,GABALDON BITULOK AND SABANI,20,"[2016, 2019]",NaN,GABALDON,10,10,GABALDON
43,ORIENTAL MINDORO,BULALACAO SAN PEDRO,40,"[2004, 2007, 2016, 2019]",NaN,BULALACAO,10,10,BULALACAO
44,PALAWAN,BROOKE S POINT,20,"[2004, 2007]",BROOKES POINT,BROOKES POINT,10,10,BROOKES POINT
45,PAMPANGA,SASMUAN SEXMOAN,40,"[2004, 2007, 2016, 2019]",NaN,SASMUAN,9,9,SASMUAN
46,PAMPANGA,STO TOMAS,10,[2025],SANTO TOMAS,NaN,0,8,SANTO TOMAS
47,PANGASINAN,POZORRUBIO,59,"[2004, 2013, 2016, 2019, 2022, 2025]",POZZORUBIO,POZZORUBIO,9,9,POZZORUBIO
48,SOUTH COTABATO,GENERAL SANTOS CITY DADIANGAS,46,"[2004, 2007, 2016, 2019]",NaN,GENERAL SANTOS,12,12,GENERAL SANTOS
49,SOUTH COTABATO,T BOLI,28,"[2001, 2004, 2007]",TBOLI,TBOLI,8,10,TBOLI
50,SOUTHERN LEYTE,SAN JUAN CABALIAN,50,"[2004, 2010, 2013, 2016, 2019]",NaN,SAN JUAN,10,10,SAN JUAN
51,SULU,HADJI PANGLIMA TAHIL MARUNGGAS,50,"[2004, 2007, 2010, 2016, 2019]",HADJI PANGLIMA TAHIL,HADJI PANGLIMA TAHIL,10,10,HADJI PANGLIMA TAHIL
52,SULU,JOLO CAPITAL,20,"[2004, 2007]",NaN,JOLO,8,8,JOLO
53,SULU,PANGLIMA ESTINO NEW PANAMAO,49,"[2004, 2007, 2010, 2016, 2019]",NaN,PANGLIMA ESTINO,8,8,PANGLIMA ESTINO
54,ZAMBOANGA DEL NORTE,BACUNGAN LEON T POSTIGO,40,"[2004, 2007, 2016, 2019]",NaN,BACUNGAN,10,10,BACUNGAN
55,ZAMBOANGA DEL NORTE,LEON T POSTIGO,10,[2025],NaN,NaN,0,10,NaN

In [11]:
decisions = {
    "TUGUNAN": None,                           # a new town in the Special Geographic Area (2025), not TULUNAN
    "KALOOCAN": "CALOOCAN",                    # official spelling
    "KALOOKAN": "CALOOCAN",                    # HF's other spelling of the same city
    "AMAI MANABILANG": "BUMBARAN",             # the town's new name; HF uses the old one
    "LEON T POSTIGO": "BACUNGAN",              # the town's new name; HF uses the old one
    "SHARIFF AGUAK CAPITAL": "SHARIFF AGUAK",  # same name plus "capital"
}
fixes = dict(zip(review_oh["town_std"], review_oh["suggestion"]))
fixes.update(decisions)
for town, std in sorted(fixes.items()):
    if pd.notna(std):
        print(f'    "{town}": "{std}",')
print("no change (new towns):", sorted(t for t, s in fixes.items() if pd.isna(s)))

    "AMAI MANABILANG": "BUMBARAN",
    "AMAI MANABILANG BUMBARAN": "BUMBARAN",
    "BACOLOD KALAWI BACOLOD GRANDE": "BACOLOD KALAWI",
    "BACUNGAN LEON T POSTIGO": "BACUNGAN",
    "BALIWAG": "BALIUAG",
    "BANAY BANAY": "BANAYBANAY",
    "BAYAWAN CITY TULONG": "BAYAWAN",
    "BINDOY PAYABON": "BINDOY",
    "BROOKE S POINT": "BROOKES POINT",
    "BULALACAO SAN PEDRO": "BULALACAO",
    "D V CHIONGBIAN D M MARCOS": "DON VICTORIANO CHIONGBIAN",
    "DON V CHIONGBIAN": "DON VICTORIANO CHIONGBIAN",
    "DUMAGUETE CITY CAPITAL": "DUMAGUETE",
    "GABALDON BITULOK & SABANI": "GABALDON",
    "GABALDON BITULOK AND SABANI": "GABALDON",
    "GENERAL SANTOS CITY DADIANGAS": "GENERAL SANTOS",
    "GETAFE": "JETAFE",
    "HADJI PANGLIMA TAHIL MARUNGGAS": "HADJI PANGLIMA TAHIL",
    "JAVIER BUGHO": "JAVIER",
    "JOLO CAPITAL": "JOLO",
    "KABUGAO CAPITAL": "KABUGAO",
    "KALOOCAN": "CALOOCAN",
    "KALOOKAN": "CALOOCAN",
    "LA TRINIDAD CAPITAL": "LA TRINIDAD",
    "LAGAWE BURNAY": "LAGAWE",
    "LEON T POSTIGO": "BACUNGAN",
    "M LANG": "MLANG",
    "MASUI": "MASIU",
    "MATAASNAKAHOY": "MATAAS NA KAHOY",
    "PAGAYAWAN TATARIKAN": "PAGAYAWAN",
    "PANGLIMA ESTINO NEW PANAMAO": "PANGLIMA ESTINO",
    "PARACELIS PARACALES": "PARACELIS",
    "PINAMUNGAJAN": "PINAMUNGAHAN",
    "PIO V CORPUS": "PIO V CORPUZ",
    "POZORRUBIO": "POZZORUBIO",
    "S N DIMAPORO KAROMATAN": "SULTAN NAGA DIMAPORO",
    "SAL LAPADAN": "SALLAPADAN",
    "SALCEDO BAUGEN": "SALCEDO",
    "SAN JUAN CABALIAN": "SAN JUAN",
    "SAN JUAN LAPOG": "SAN JUAN",
    "SAN POLICARPIO": "SAN POLICARPO",
    "SASMUAN SEXMOAN": "SASMUAN",
    "SHARIFF AGUAK CAPITAL": "SHARIFF AGUAK",
    "STO TOMAS": "SANTO TOMAS",
    "SULTAN GUMANDER": "PICONG",
    "SULTAN NAGA DIMAPORO KAROMATAN": "SULTAN NAGA DIMAPORO",
    "T BOLI": "TBOLI",
    "TACLOBAN CITY CAPITAL": "TACLOBAN",
no change (new towns): ['KADAYANGAN', 'KAPALAWAN', 'LIGAWASAN', 'MALIDEGAO', 'NABALAWAG', 'OLD KAABAKAN', 'PAHAMUDDIN', 'TUGUNAN']

### Summary: OpenHalalan names

- 56 OpenHalalan town names (1,372 rows) were never used by HF. 48 are the same towns written differently: an old name or "capital" attached (SALCEDO BAUGEN, JOLO CAPITAL), a spelling (POZORRUBIO, T BOLI), or a newer official name (GETAFE → JETAFE, AMAI MANABILANG → BUMBARAN). They were added to `TOWN_MAP` with HF's spelling as the standard. Caloocan's three spellings (CALOOCAN, KALOOCAN, KALOOKAN) are now one.
- The other 8 are new towns first elected in 2025 (Special Geographic Area), so they stay as they are. The code suggested TULUNAN for TUGUNAN, and we rejected it.
- Effect on the existing outputs: 1,435 OpenHalalan rows now use HF's spelling, 42 HF rows changed from KALOOKAN to CALOOCAN, and 4 more HF rows got a town (SASMUAN, BAYAWAN, MLANG). Persons, the ID map, PSA and the roster did not change.

### 3b. Ateneo names that no other source has

In [12]:
import importlib
import src.transform.mappings
import src.transform.clean_backfill
importlib.reload(src.transform.mappings)        # the notebook still holds the old maps in memory,
importlib.reload(src.transform.clean_backfill)  # so reload both, mappings first
from src.transform.clean_backfill import clean_ateneo_politicians, known_town_pairs

memberships = pd.read_parquet(STAGING / "hf_memberships_clean.parquet")
winners = pd.read_parquet(STAGING / "openhalalan_winners_clean.parquet")
at = clean_ateneo_politicians(ateneo, known_town_pairs(memberships, winners))
unverified = at[at["town_verified"].eq(False)]
review_at = suggest_town_fixes(unverified, at[at["town_verified"].eq(True)])
print(len(review_at), "Ateneo town names in", review_at["rows"].sum(), "rows | with a suggestion:", review_at["suggestion"].notna().sum())
pd.set_option("display.max_rows", 200)
review_at[["province_group", "town_std", "rows", "years", "spelling", "shared_town", "shared", "of", "suggestion"]]

115 Ateneo town names in 1511 rows | with a suggestion: 102

,province_group,town_std,rows,years,spelling,shared_town,shared,of,suggestion
0,ABRA,BAAY LICUAN,20,"[1992, 1998]",NaN,BUCLOC,3,10,BUCLOC
1,ABRA,LICUAN BAY,10,[1988],LICUAN BAAY,LICUAN BAAY,2,10,LICUAN BAAY
2,BATANGAS,SAN PACUAL,10,[1998],SAN PASCUAL,SAN PASCUAL,10,10,SAN PASCUAL
3,BOHOL,ANTEQUERRA,10,[1992],ANTEQUERA,ANTEQUERA,7,8,ANTEQUERA
4,BOHOL,CATIGBI AN,10,[1992],CATIGBIAN,CATIGBIAN,7,10,CATIGBIAN
5,BOHOL,PRES CP GARCIA,20,"[1995, 1998]",NaN,PRESIDENT CARLOS P GARCIA,6,10,PRESIDENT CARLOS P GARCIA
6,BOHOL,PRES GARCIA,10,[1992],NaN,PRESIDENT CARLOS P GARCIA,5,10,PRESIDENT CARLOS P GARCIA
7,BOHOL,PRESIDENTE CARLOS P GARCIA,10,[1988],PRESIDENT CARLOS P GARCIA,MABINI,2,10,PRESIDENT CARLOS P GARCIA
8,BUKIDNON,IMPASUGONG,10,[1998],IMPASUG ONG,IMPASUG ONG,5,10,IMPASUG ONG
9,BUKIDNON,MALAYBALAYY,10,[1988],MALAYBALAY,MALAYBALAY,4,10,MALAYBALAY
10,BULACAN,BUSANTO S,10,[1988],BUSTOS,BUSTOS,5,8,BUSTOS
11,CAGAYAN,LALLO,10,[1998],LAL LO,LAL LO,8,10,LAL LO
12,CAMARINES SUR,GARCHITORINA,10,[1988],GARCHITORENA,CARAMOAN,3,10,GARCHITORENA
13,CAMARINES SUR,SAN AGUSTIN,10,[1988],NaN,NaN,0,10,NaN
14,CAPIZ,MAAYON,10,[1998],MA AYON,MA AYON,6,10,MA AYON
15,CAPIZ,SAPIAN,10,[1998],SAPI AN,SAPI AN,4,10,SAPI AN
16,CAVITE,GEN E AGUINALDO,10,[1998],NaN,GENERAL EMILIO AGUINALDO,7,10,GENERAL EMILIO AGUINALDO
17,CAVITE,GEN M ALVAREZ,10,[1998],GEN MARIANO ALVAREZ,GEN MARIANO ALVAREZ,6,10,GEN MARIANO ALVAREZ
18,CAVITE,GEN TRIAS,10,[1998],GENERAL TRIAS,GENERAL TRIAS,6,8,GENERAL TRIAS
19,CAVITE,GENERAL MARIANO ALVAREZ,10,[1988],GEN MARIANO ALVAREZ,GEN MARIANO ALVAREZ,5,10,GEN MARIANO ALVAREZ
20,CAVITE,MENDEZ NUNEZ,40,"[1988, 1992, 1995, 1998]",NaN,ALFONSO,1,10,NaN
21,CAVITE,NOVOLETA,10,[1988],NOVELETA,NOVELETA,9,10,NOVELETA
22,CEBU,BOUOON,10,[1988],NaN,BOLJOON,3,10,BOLJOON
23,CEBU,MADRILEJOS,10,[1992],MADRIDEJOS,MADRIDEJOS,3,10,MADRIDEJOS
24,CEBU,SAN REMEGIO,10,[1988],SAN REMIGIO,SAN REMIGIO,5,9,SAN REMIGIO
25,COTABATO,MILANG,10,[1988],MLANG,MLANG,5,10,MLANG
26,COTABATO,PIGCAWAYAN,10,[1988],PIGKAWAYAN,PIGKAWAYAN,6,10,PIGKAWAYAN
27,DAVAO DEL NORTE,BABAK,20,"[1988, 1992]",NaN,BRAULIO E DUJALI,5,10,BRAULIO E DUJALI
28,DAVAO DEL NORTE,KAPUT IAN,10,[1988],NaN,ISLAND GARDEN CITY OF SAMAL,1,10,NaN
29,DAVAO DEL NORTE,KAPUTIAN,20,"[1992, 1995]",NaN,CARMEN,1,10,NaN
30,DAVAO DEL NORTE,MONTEVISANTA,10,[1988],MONTEVISTA,MONTEVISTA,6,10,MONTEVISTA
31,DAVAO DEL NORTE,SAMAL,30,"[1988, 1992, 1995]",NaN,ASUNCION,1,10,NaN
32,DAVAO DEL NORTE,SAN MARIANO,10,[1988],NaN,MARAGUSAN,9,10,MARAGUSAN
33,DAVAO DEL NORTE,SAN VICENTE,10,[1988],NaN,LAAK,7,10,LAAK
34,DAVAO DEL SUR,MAUTA,10,[1988],NaN,MALITA,8,10,MALITA
35,DAVAO DEL SUR,PALADA,10,[1988],NaN,PADADA,9,10,PADADA
36,EASTERN SAMAR,GEN MACARTHUR,10,[1998],GENERAL MACARTHUR,GENERAL MACARTHUR,7,9,GENERAL MACARTHUR
37,EASTERN SAMAR,GENERAL MACARHUR,20,"[1992, 1995]",GENERAL MACARTHUR,GENERAL MACARTHUR,4,9,GENERAL MACARTHUR
38,EASTERN SAMAR,GENERAL MCARTHUR,10,[1988],GENERAL MACARTHUR,SAN POLICARPO,2,10,GENERAL MACARTHUR
39,EASTERN SAMAR,LAWA AN,20,"[1988, 1998]",LAWAAN,LAWAAN,4,10,LAWAAN
40,IFUGAO,AGUINALDC,10,[1988],AGUINALDO,AGUINALDO,2,10,AGUINALDO
41,IFUGAO,POTIA,10,[1988],NaN,ALFONSO LISTA,3,10,ALFONSO LISTA
42,ILOCOS NORTE,ESPIRITU,40,"[1988, 1992, 1995, 1998]",NaN,DINGRAS,1,9,NaN
43,ILOCOS NORTE,NUEVA ECIJA,10,[1988],NUEVA ERA,NUEVA ERA,6,10,NUEVA ERA
44,ILOCOS SUR,NARVARCAN,10,[1988],NARVACAN,NARVACAN,9,10,NARVACAN
45,ISABELA,CAUAYAM,10,[1988],CAUAYAN,CAUAYAN,8,10,CAUAYAN
46,ISABELA,DIVILICAN,18,"[1988, 1998]",DIVILACAN,DIVILACAN,1,8,DIVILACAN
47,LAGUNA,KALAYAN,10,[1988],KALAYAAN,KALAYAAN,3,9,KALAYAAN
48,LAGUNA,SINLOAN,10,[1988],SINILOAN,SINILOAN,7,9,SINILOAN
49,LANAO DEL NORTE,BALO I,30,"[1988, 1992, 1995]",BALOI,BALOI,1,9,BALOI
50,LANAO DEL NORTE,KAROMATAN,20,"[1988, 1992]",NaN,SULTAN NAGA DIMAPORO,4,10,SULTAN NAGA DIMAPORO
51,LANAO DEL SUR,BACOLOD GRANDE,30,"[1988, 1992, 1995]",NaN,BINIDAYAN,1,10,NaN
52,LANAO DEL SUR,BUADIPUSO BUNTONG,11,"[1988, 1998]",BUADIPOSO BUNTONG,CALANOGAS,2,9,BUADIPOSO BUNTONG
53,LANAO DEL SUR,LUMBAYANGUE,10,[1988],LUMBAYANAGUE,MADALUM,2,10,LUMBAYANAGUE
54,LANAO DEL SUR,MAO,10,[1988],NaN,WAO,7,10,WAO
55,LANAO DEL SUR,MOLUNDO,10,[1998],NaN,MULONDO,5,10,MULONDO
56,LEYTE,V ALANGALANG,10,[1988],ALANGALANG,ALANGALANG,6,8,ALANGALANG
57,MAGUINDANAO,BOLUAN,10,[1988],BULUAN,BULUAN,4,10,BULUAN
58,MAGUINDANAO,DINAIG,19,"[1988, 1992]",NaN,DATU ODIN SINSUAT,1,9,NaN
59,MAGUINDANAO,GEN SK PENDATUN,30,"[1992, 1995, 1998]",GEN S K PENDATUN,GEN S K PENDATUN,3,8,GEN S K PENDATUN
60,MAGUINDANAO,MAGANOY,9,[1988],NaN,NaN,0,9,NaN
61,MAGUINDANAO,MAGANOY CAPITAL,20,"[1992, 1995]",NaN,SHARIFF AGUAK,3,8,SHARIFF AGUAK
62,MAGUINDANAO,MARAWI,12,[1995],NaN,BARIRA,1,12,NaN
63,MAGUINDANAO,SULTAN SA MAROMATA,10,[1988],NaN,SULTAN SA BARONGIS,2,9,NaN
64,MASBATE,PIO VCORPUZ,10,[1988],PIO V CORPUZ,PIO V CORPUZ,3,10,PIO V CORPUZ
65,MISAMIS OCCIDENTAL,DON MARIANO MARCOS,10,[1988],NaN,DON VICTORIANO CHIONGBIAN,5,10,DON VICTORIANO CHIONGBIAN
66,MISAMIS OCCIDENTAL,OZAMIZ,12,[1988],OZAMIS,OZAMIS,8,12,OZAMIS
67,MISAMIS ORIENTAL,BINUANIGAN,10,[1988],BINUANGAN,BINUANGAN,6,9,BINUANGAN
68,MISAMIS ORIENTAL,KINOGITAN,20,"[1988, 1998]",KINOGUITAN,KINOGUITAN,2,10,KINOGUITAN
69,NCR FOURTH DISTRICT,TAGIG,28,"[1992, 1995]",TAGUIG,TAGUIG,5,13,TAGUIG
70,NCR THIRD DISTRICT,MALABON NAVOTAS,14,[1992],NaN,NAVOTAS,12,14,NAVOTAS
71,NEGROS OCCIDENTAL,E B MAGALONA,10,[1998],ENRIQUE B MAGALONA,ENRIQUE B MAGALONA,7,10,ENRIQUE B MAGALONA
72,NEGROS OCCIDENTAL,ENRIQUE BMAGALONA,10,[1988],ENRIQUE B MAGALONA,ENRIQUE B MAGALONA,6,10,ENRIQUE B MAGALONA
73,NEGROS OCCIDENTAL,SAN SILAY,12,[1988],NaN,SILAY,6,11,SILAY
74,NUEVA ECIJA,GEN NATIVIDAD,10,[1998],NaN,GENERAL MAMERTO NATIVIDAD,6,10,GENERAL MAMERTO NATIVIDAD
75,NUEVA ECIJA,GEN TINIO,15,[1998],GENERAL TINIO,GENERAL TINIO,4,10,GENERAL TINIO
76,NUEVA ECIJA,MUNOZ,30,"[1988, 1995, 1998]",NaN,ALIAGA,2,10,NaN
77,NUEVA ECIJA,PANARANDA,10,[1988],PENARANDA,PENARANDA,4,9,PENARANDA
78,NUEVA ECIJA,TALUGTOG,10,[1998],TALUGTUG,TALUGTUG,5,9,TALUGTUG
79,NUEVA ECIJA,ZARAGOSA,10,[1998],ZARAGOZA,ZARAGOZA,7,10,ZARAGOZA
80,NUEVA VIZCAYA,ALFREDO CASTANEDA,8,[1988],ALFONSO CASTANEDA,ALFONSO CASTANEDA,3,7,ALFONSO CASTANEDA
81,NUEVA VIZCAYA,VILLA VERDE,10,[1988],VILLAVERDE,VILLAVERDE,2,10,VILLAVERDE
82,OCCIDENTAL MINDORO,ABRA DEL ILOG,10,[1998],ABRA DE ILOG,ABRA DE ILOG,7,10,ABRA DE ILOG
83,ORIENTAL MINDORO,BULALAKAO,10,[1998],BULALACAO,BULALACAO,8,10,BULALACAO
84,PALAWAN,BATARASA,10,[1998],BATARAZA,BATARAZA,8,10,BATARAZA
85,PALAWAN,MARCOS,9,[1988],NaN,RIZAL,5,9,RIZAL
86,PAMPANGA,SEXMOAN,10,[1988],NaN,SASMUAN,5,10,SASMUAN
87,PANGASINAN,AG NO,10,[1988],AGNO,AGNO,5,10,AGNO
88,QUEZON,JUMALIG,20,"[1992, 1995]",JOMALIG,JOMALIG,4,10,JOMALIG
89,RIZAL,JALAJALA,10,[1988],JALA JALA,JALA JALA,3,10,JALA JALA
90,ROMBLON,SAN LORENZO RUIZ,10,[1988],NaN,SANTA MARIA,6,10,SANTA MARIA
91,SAMAR,TARAGNAN,10,[1988],TARANGNAN,TARANGNAN,4,10,TARANGNAN
92,SAMAR,WRIGHT,10,[1988],NaN,PARANAS,3,10,PARANAS
93,SORSOGON,BACON,40,"[1988, 1992, 1995, 1998]",NaN,CASIGURAN,1,10,NaN
94,SOUTH COTABATO,GEN SANTOS,14,[1998],GENERAL SANTOS,GENERAL SANTOS,9,14,GENERAL SANTOS
95,SULTAN KUDARAT,LEBAE,10,[1988],LEBAK,LEBAK,5,10,LEBAK
96,SULTAN KUDARAT,PRES QUIRINO,10,[1998],PRESIDENT QUIRINO,PRESIDENT QUIRINO,5,10,PRESIDENT QUIRINO
97,SULU,KALINGGALAN CALUANG,10,[1988],KALINGALAN CALUANG,PANGUTARAN,1,10,KALINGALAN CALUANG
98,SULU,MARUNGAS,10,[1988],NaN,HADJI PANGLIMA TAHIL,3,10,HADJI PANGLIMA TAHIL
99,SULU,MARUNGGAS,20,"[1992, 1995]",NaN,HADJI PANGLIMA TAHIL,3,10,HADJI PANGLIMA TAHIL
100,SULU,NEW PANAMAO,10,[1988],NaN,PANGLIMA ESTINO,3,8,PANGLIMA ESTINO
101,SULU,PANAMAO,20,"[1988, 1998]",NaN,OLD PANAMAO,8,10,OLD PANAMAO
102,SURIGAO DEL NORTE,GEN LUNA,10,[1998],GENERAL LUNA,GENERAL LUNA,5,7,GENERAL LUNA
103,SURIGAO DEL NORTE,GIGAGUIT,10,[1988],GIGAQUIT,GIGAQUIT,5,10,GIGAQUIT
104,SURIGAO DEL NORTE,LIBIO,10,[1988],LIBJO,LIBJO,6,10,LIBJO
105,SURIGAO DEL SUR,BOROBO,10,[1988],BAROBO,BAROBO,4,10,BAROBO
106,SURIGAO DEL SUR,CASWAIT,10,[1988],CAGWAIT,CAGWAIT,7,9,CAGWAIT
107,TAWI TAWI,BALIMBING,10,[1988],NaN,PANGLIMA SUGALA,5,10,PANGLIMA SUGALA
108,TAWI TAWI,CAGAYAN DE TAW,10,[1988],NaN,MAPUN,4,10,MAPUN
109,ZAMBOANGA DEL NORTE,JOSE DALMAN (PONOD,10,[1988],NaN,JOSE DALMAN,5,9,JOSE DALMAN
110,ZAMBOANGA DEL NORTE,LEON B POSTIGO,10,[1998],NaN,BACUNGAN,8,10,BACUNGAN
111,ZAMBOANGA DEL NORTE,PRESIDENT ROXAS,10,[1988],NaN,PRES MANUEL A ROXAS,8,10,PRES MANUEL A ROXAS
112,ZAMBOANGA DEL NORTE,SERGIO OSMENHA SR,10,[1988],SERGIO OSMENA SR,SERGIO OSMENA SR,3,10,SERGIO OSMENA SR
113,ZAMBOANGA DEL SUR,DON MARIANO MARCOS,10,[1988],NaN,SOMINOT,6,10,SOMINOT
114,ZAMBOANGA DEL SUR,VINCENZO SAGUN,10,[1988],VINCENZO A SAGUN,VINCENZO A SAGUN,4,10,VINCENZO A SAGUN

In [13]:
decisions = {
    ("ABRA", "BAAY LICUAN"): "LICUAN BAAY",                # words swapped; BUCLOC is listed separately in those years
    ("CAVITE", "MENDEZ NUNEZ"): "MENDEZ",                  # former name
    ("DAVAO DEL NORTE", "BABAK"): None,                    # a real town until 1998 (historical)
    ("DAVAO DEL NORTE", "KAPUT IAN"): "KAPUTIAN",          # spelling of a historical town
    ("ILOCOS NORTE", "ESPIRITU"): "BANNA",                 # former name, written "ESPIRITU (BANNA)"
    ("LANAO DEL SUR", "BACOLOD GRANDE"): "BACOLOD KALAWI", # former name
    ("MAGUINDANAO", "DINAIG"): "DATU ODIN SINSUAT",        # former name
    ("MAGUINDANAO", "MAGANOY"): "SHARIFF AGUAK",           # former name
    ("NUEVA ECIJA", "MUNOZ"): "SCIENCE CITY OF MUNOZ",     # became a city in 2000
}
fixes = dict(zip(zip(review_at["province_group"], review_at["town_std"]), review_at["suggestion"]))
fixes.update(decisions)
for (group, town), std in sorted(fixes.items()):
    if pd.notna(std):
        print(f'    ("{group}", "{town}"): "{std}",')
print("no fix:", sorted(key for key, std in fixes.items() if pd.isna(std)))

    ("ABRA", "BAAY LICUAN"): "LICUAN BAAY",
    ("ABRA", "LICUAN BAY"): "LICUAN BAAY",
    ("BATANGAS", "SAN PACUAL"): "SAN PASCUAL",
    ("BOHOL", "ANTEQUERRA"): "ANTEQUERA",
    ("BOHOL", "CATIGBI AN"): "CATIGBIAN",
    ("BOHOL", "PRES CP GARCIA"): "PRESIDENT CARLOS P GARCIA",
    ("BOHOL", "PRES GARCIA"): "PRESIDENT CARLOS P GARCIA",
    ("BOHOL", "PRESIDENTE CARLOS P GARCIA"): "PRESIDENT CARLOS P GARCIA",
    ("BUKIDNON", "IMPASUGONG"): "IMPASUG ONG",
    ("BUKIDNON", "MALAYBALAYY"): "MALAYBALAY",
    ("BULACAN", "BUSANTO S"): "BUSTOS",
    ("CAGAYAN", "LALLO"): "LAL LO",
    ("CAMARINES SUR", "GARCHITORINA"): "GARCHITORENA",
    ("CAPIZ", "MAAYON"): "MA AYON",
    ("CAPIZ", "SAPIAN"): "SAPI AN",
    ("CAVITE", "GEN E AGUINALDO"): "GENERAL EMILIO AGUINALDO",
    ("CAVITE", "GEN M ALVAREZ"): "GEN MARIANO ALVAREZ",
    ("CAVITE", "GEN TRIAS"): "GENERAL TRIAS",
    ("CAVITE", "GENERAL MARIANO ALVAREZ"): "GEN MARIANO ALVAREZ",
    ("CAVITE", "MENDEZ NUNEZ"): "MENDEZ",
    ("CAVITE", "NOVOLETA"): "NOVELETA",
    ("CEBU", "BOUOON"): "BOLJOON",
    ("CEBU", "MADRILEJOS"): "MADRIDEJOS",
    ("CEBU", "SAN REMEGIO"): "SAN REMIGIO",
    ("COTABATO", "MILANG"): "MLANG",
    ("COTABATO", "PIGCAWAYAN"): "PIGKAWAYAN",
    ("DAVAO DEL NORTE", "KAPUT IAN"): "KAPUTIAN",
    ("DAVAO DEL NORTE", "MONTEVISANTA"): "MONTEVISTA",
    ("DAVAO DEL NORTE", "SAN MARIANO"): "MARAGUSAN",
    ("DAVAO DEL NORTE", "SAN VICENTE"): "LAAK",
    ("DAVAO DEL SUR", "MAUTA"): "MALITA",
    ("DAVAO DEL SUR", "PALADA"): "PADADA",
    ("EASTERN SAMAR", "GEN MACARTHUR"): "GENERAL MACARTHUR",
    ("EASTERN SAMAR", "GENERAL MACARHUR"): "GENERAL MACARTHUR",
    ("EASTERN SAMAR", "GENERAL MCARTHUR"): "GENERAL MACARTHUR",
    ("EASTERN SAMAR", "LAWA AN"): "LAWAAN",
    ("IFUGAO", "AGUINALDC"): "AGUINALDO",
    ("IFUGAO", "POTIA"): "ALFONSO LISTA",
    ("ILOCOS NORTE", "ESPIRITU"): "BANNA",
    ("ILOCOS NORTE", "NUEVA ECIJA"): "NUEVA ERA",
    ("ILOCOS SUR", "NARVARCAN"): "NARVACAN",
    ("ISABELA", "CAUAYAM"): "CAUAYAN",
    ("ISABELA", "DIVILICAN"): "DIVILACAN",
    ("LAGUNA", "KALAYAN"): "KALAYAAN",
    ("LAGUNA", "SINLOAN"): "SINILOAN",
    ("LANAO DEL NORTE", "BALO I"): "BALOI",
    ("LANAO DEL NORTE", "KAROMATAN"): "SULTAN NAGA DIMAPORO",
    ("LANAO DEL SUR", "BACOLOD GRANDE"): "BACOLOD KALAWI",
    ("LANAO DEL SUR", "BUADIPUSO BUNTONG"): "BUADIPOSO BUNTONG",
    ("LANAO DEL SUR", "LUMBAYANGUE"): "LUMBAYANAGUE",
    ("LANAO DEL SUR", "MAO"): "WAO",
    ("LANAO DEL SUR", "MOLUNDO"): "MULONDO",
    ("LEYTE", "V ALANGALANG"): "ALANGALANG",
    ("MAGUINDANAO", "BOLUAN"): "BULUAN",
    ("MAGUINDANAO", "DINAIG"): "DATU ODIN SINSUAT",
    ("MAGUINDANAO", "GEN SK PENDATUN"): "GEN S K PENDATUN",
    ("MAGUINDANAO", "MAGANOY"): "SHARIFF AGUAK",
    ("MAGUINDANAO", "MAGANOY CAPITAL"): "SHARIFF AGUAK",
    ("MASBATE", "PIO VCORPUZ"): "PIO V CORPUZ",
    ("MISAMIS OCCIDENTAL", "DON MARIANO MARCOS"): "DON VICTORIANO CHIONGBIAN",
    ("MISAMIS OCCIDENTAL", "OZAMIZ"): "OZAMIS",
    ("MISAMIS ORIENTAL", "BINUANIGAN"): "BINUANGAN",
    ("MISAMIS ORIENTAL", "KINOGITAN"): "KINOGUITAN",
    ("NCR FOURTH DISTRICT", "TAGIG"): "TAGUIG",
    ("NCR THIRD DISTRICT", "MALABON NAVOTAS"): "NAVOTAS",
    ("NEGROS OCCIDENTAL", "E B MAGALONA"): "ENRIQUE B MAGALONA",
    ("NEGROS OCCIDENTAL", "ENRIQUE BMAGALONA"): "ENRIQUE B MAGALONA",
    ("NEGROS OCCIDENTAL", "SAN SILAY"): "SILAY",
    ("NUEVA ECIJA", "GEN NATIVIDAD"): "GENERAL MAMERTO NATIVIDAD",
    ("NUEVA ECIJA", "GEN TINIO"): "GENERAL TINIO",
    ("NUEVA ECIJA", "MUNOZ"): "SCIENCE CITY OF MUNOZ",
    ("NUEVA ECIJA", "PANARANDA"): "PENARANDA",
    ("NUEVA ECIJA", "TALUGTOG"): "TALUGTUG",
    ("NUEVA ECIJA", "ZARAGOSA"): "ZARAGOZA",
    ("NUEVA VIZCAYA", "ALFREDO CASTANEDA"): "ALFONSO CASTANEDA",
    ("NUEVA VIZCAYA", "VILLA VERDE"): "VILLAVERDE",
    ("OCCIDENTAL MINDORO", "ABRA DEL ILOG"): "ABRA DE ILOG",
    ("ORIENTAL MINDORO", "BULALAKAO"): "BULALACAO",
    ("PALAWAN", "BATARASA"): "BATARAZA",
    ("PALAWAN", "MARCOS"): "RIZAL",
    ("PAMPANGA", "SEXMOAN"): "SASMUAN",
    ("PANGASINAN", "AG NO"): "AGNO",
    ("QUEZON", "JUMALIG"): "JOMALIG",
    ("RIZAL", "JALAJALA"): "JALA JALA",
    ("ROMBLON", "SAN LORENZO RUIZ"): "SANTA MARIA",
    ("SAMAR", "TARAGNAN"): "TARANGNAN",
    ("SAMAR", "WRIGHT"): "PARANAS",
    ("SOUTH COTABATO", "GEN SANTOS"): "GENERAL SANTOS",
    ("SULTAN KUDARAT", "LEBAE"): "LEBAK",
    ("SULTAN KUDARAT", "PRES QUIRINO"): "PRESIDENT QUIRINO",
    ("SULU", "KALINGGALAN CALUANG"): "KALINGALAN CALUANG",
    ("SULU", "MARUNGAS"): "HADJI PANGLIMA TAHIL",
    ("SULU", "MARUNGGAS"): "HADJI PANGLIMA TAHIL",
    ("SULU", "NEW PANAMAO"): "PANGLIMA ESTINO",
    ("SULU", "PANAMAO"): "OLD PANAMAO",
    ("SURIGAO DEL NORTE", "GEN LUNA"): "GENERAL LUNA",
    ("SURIGAO DEL NORTE", "GIGAGUIT"): "GIGAQUIT",
    ("SURIGAO DEL NORTE", "LIBIO"): "LIBJO",
    ("SURIGAO DEL SUR", "BOROBO"): "BAROBO",
    ("SURIGAO DEL SUR", "CASWAIT"): "CAGWAIT",
    ("TAWI TAWI", "BALIMBING"): "PANGLIMA SUGALA",
    ("TAWI TAWI", "CAGAYAN DE TAW"): "MAPUN",
    ("ZAMBOANGA DEL NORTE", "JOSE DALMAN (PONOD"): "JOSE DALMAN",
    ("ZAMBOANGA DEL NORTE", "LEON B POSTIGO"): "BACUNGAN",
    ("ZAMBOANGA DEL NORTE", "PRESIDENT ROXAS"): "PRES MANUEL A ROXAS",
    ("ZAMBOANGA DEL NORTE", "SERGIO OSMENHA SR"): "SERGIO OSMENA SR",
    ("ZAMBOANGA DEL SUR", "DON MARIANO MARCOS"): "SOMINOT",
    ("ZAMBOANGA DEL SUR", "VINCENZO SAGUN"): "VINCENZO A SAGUN",
no fix: [('CAMARINES SUR', 'SAN AGUSTIN'), ('DAVAO DEL NORTE', 'BABAK'), ('DAVAO DEL NORTE', 'KAPUTIAN'), ('DAVAO DEL NORTE', 'SAMAL'), ('MAGUINDANAO', 'MARAWI'), ('MAGUINDANAO', 'SULTAN SA MAROMATA'), ('SORSOGON', 'BACON')]

In [14]:
importlib.reload(src.transform.mappings)
importlib.reload(src.transform.clean_backfill)
from src.transform.clean_backfill import clean_ateneo_politicians, known_town_pairs

at = clean_ateneo_politicians(ateneo, known_town_pairs(memberships, winners))
print("town_verified:", at["town_verified"].value_counts(dropna=False).to_dict())
at[at["town_verified"].eq(False)].groupby(["year", "province", "municipality", "town_std"]).size()

town_verified: {True: 172344, nan: 35223, False: 32}

year  province       municipality                 town_std
1988  CAMARINES SUR  SAN AGUSTIN                  SAN AGUSTIN           10
      MAGUINDANAO    SULTAN SA MAROMATA           SULTAN SA MAROMATA    10
1995  MAGUINDANAO    MARAWI CITY (LANAO DEL SUR)  MARAWI                12
dtype: int64

### Summary: Ateneo names

- 115 Ateneo town names (1,511 rows, 1988 to 1998) were in neither HF nor OpenHalalan. 108 now map to a known town in `PROVINCE_TOWN_MAP`. 100 come from the code's suggestions: mostly spelling slips (TAGIG → TAGUIG), and 1988 scanning errors confirmed by the officials' surnames (MAUTA → MALITA, 8 of 10 surnames shared). 8 were decided by hand: former names (MUNOZ → SCIENCE CITY OF MUNOZ, ESPIRITU → BANNA), swapped words (BAAY LICUAN → LICUAN BAAY), and a spacing typo (KAPUT IAN). Two suggestions were rejected: BAAY LICUAN → BUCLOC and BABAK → BRAULIO E DUJALI.
- Four were real towns that later merged into cities (BABAK, KAPUTIAN, SAMAL, BACON). They keep their names and are listed in `HISTORICAL_TOWNS`.
- 32 rows remain unverified: SAN AGUSTIN (Camarines Sur, 1988) and SULTAN SA MAROMATA (Maguindanao, 1988), where no clue is strong enough, and Marawi, which was filed under Maguindanao in 1995 (fixed in section 4).

## 4. Town label check

A town name can be real and still be the wrong label for a group of rows. Families usually stay in the same town, so each town's officials should share some surnames with the same town in the next election. `label_suspects` flags town-years whose officials share at most 1 surname with their own town in the next election, but at least 4 with another town of the same province.

In [15]:
from src.utils.town_review import label_suspects

suspects = label_suspects(at[at["town_verified"].eq(True)])
print(len(suspects), "town-years whose officials look like another town's")
suspects

10 town-years whose officials look like another town's

,province_group,year,town_std,officials,shared_with_itself,next_year,best_other,shared_with_other
0,BULACAN,1998,BULACAN,8,0,2001,BOCAUE,6
1,DAVAO DEL NORTE,1992,BABAK,9,0,1995,BRAULIO E DUJALI,7
2,DAVAO DEL NORTE,1995,BRAULIO E DUJALI,10,0,1998,ISLAND GARDEN CITY OF SAMAL,4
3,ILOCOS NORTE,2016,BANNA ESPIRITU,9,0,2019,BANNA,7
4,LEYTE,1998,BILIRAN,9,0,2001,ALMERIA,6
5,NORTHERN SAMAR,1988,SAN ROQUE,10,0,1992,SAN VICENTE,4
6,NORTHERN SAMAR,1988,SAN VICENTE,10,0,1992,SAN ROQUE,5
7,NUEVA ECIJA,1988,LAUR,10,0,1992,LUPAO,5
8,PALAWAN,1988,ROXAS,10,0,1992,SAN VICENTE,4
9,QUEZON,1998,QUEZON,10,0,2001,POLILLO,7

In [16]:
counts = at[at["town_source"].eq("original")].groupby(["year", "province_std", "town_std"]).size()
counts[(counts > 16) & (counts.index.get_level_values("year") == 2001)]

year  province_std         town_std
2001  BILIRAN              ALMERIA       20
      BULACAN              BOCAUE        20
      CEBU                 CEBU          18
      DAVAO DEL SUR        DAVAO         26
      LEYTE                LA PAZ        20
      NCR FIRST DISTRICT   MANILA        38
      NCR FOURTH DISTRICT  MAKATI        18
                           MUNTINLUPA    18
      NCR SECOND DISTRICT  QUEZON        26
      QUEZON               POLILLO       20
dtype: int64

In [17]:
from src.transform.clean_backfill import split_doubled_towns, standardize_winners

winners_std = standardize_winners(pd.read_csv(RAW / "openhalalan_winners.csv"))
at_split = split_doubled_towns(at, winners_std)
moved = at_split["town_std"].ne(at["town_std"]) & at["town_std"].notna()
print("rows given their own town:", moved.sum())
pd.DataFrame({"year": at.loc[moved, "year"], "province": at.loc[moved, "province_std"], "listed_as": at.loc[moved, "town_std"],
              "real_town": at_split.loc[moved, "town_std"]}).value_counts()

rows given their own town: 40

year  province  listed_as  real_town
2001  QUEZON    POLILLO    QUEZON       10
      LEYTE     LA PAZ     LEYTE        10
      BILIRAN   ALMERIA    BILIRAN      10
      BULACAN   BOCAUE     BULACAN      10
Name: count, dtype: int64

In [18]:
label_suspects(at_split[at_split["town_verified"].eq(True)])

,province_group,year,town_std,officials,shared_with_itself,next_year,best_other,shared_with_other
0,DAVAO DEL NORTE,1992,BABAK,9,0,1995,BRAULIO E DUJALI,7
1,DAVAO DEL NORTE,1995,BRAULIO E DUJALI,10,0,1998,ISLAND GARDEN CITY OF SAMAL,4
2,ILOCOS NORTE,2016,BANNA ESPIRITU,9,0,2019,BANNA,7
3,NORTHERN SAMAR,1988,SAN ROQUE,10,0,1992,SAN VICENTE,4
4,NORTHERN SAMAR,1988,SAN VICENTE,10,0,1992,SAN ROQUE,5
5,NUEVA ECIJA,1988,LAUR,10,0,1992,LUPAO,5
6,PALAWAN,1988,ROXAS,10,0,1992,SAN VICENTE,4

In [19]:
def surnames(df, group, year, town):
    rows = df[df["province_group"].eq(group) & df["year"].eq(year) & df["town_std"].eq(town)]
    return set(rows["last_key"])

sv_1988 = surnames(at_split, "PALAWAN", 1988, "SAN VICENTE")
for year in [1992, 1995]:
    print(f"Palawan SAN VICENTE 1988 shares with ROXAS {year}:", len(sv_1988 & surnames(at_split, "PALAWAN", year, "ROXAS")),
          f"| with SAN VICENTE {year}:", len(sv_1988 & surnames(at_split, "PALAWAN", year, "SAN VICENTE")))

at_split[at_split["town_std"].eq("MARAWI")].groupby(["year", "province"]).size().unstack(fill_value=0)

Palawan SAN VICENTE 1988 shares with ROXAS 1992: 3 | with SAN VICENTE 1992: 0
Palawan SAN VICENTE 1988 shares with ROXAS 1995: 4 | with SAN VICENTE 1995: 0

province  LANAO DEL SUR  MAGUINDANAO
year
1988                 12            0
1992                 12            0
1995                  0           12
1998                 12            0
2001                 12            0
2004                 12            0
2007                  8            0
2010                 12            0
2019                 12            0
2022                 12            0

In [ ]:
importlib.reload(src.transform.mappings)
importlib.reload(src.transform.clean_backfill)
from src.transform.clean_backfill import clean_ateneo_politicians, known_town_pairs, split_doubled_towns, standardize_winners

memberships = pd.read_parquet(STAGING / "hf_memberships_clean.parquet")
winners = pd.read_parquet(STAGING / "openhalalan_winners_clean.parquet")
winners_std = standardize_winners(pd.read_csv(RAW / "openhalalan_winners.csv"))
at = split_doubled_towns(clean_ateneo_politicians(ateneo, known_town_pairs(memberships, winners)), winners_std)
print("town_verified:", at["town_verified"].value_counts(dropna=False).to_dict())
label_suspects(at[at["town_verified"].eq(True)])

### Summary: town label check

- The check flagged 10 town-years, and each one was explained and fixed:
  - **2001 doubled towns:** Ateneo put the officials of the four towns named like their province (BULACAN, BILIRAN, LEYTE, QUEZON) under the town listed before them (BOCAUE, ALMERIA, LA PAZ, POLILLO), which then showed 20 officials instead of 10. `split_doubled_towns` gives these 40 officials their own town back, using OpenHalalan's 2001 results for the same people.
  - **Filed under the wrong place in one election** (`ATENEO_PLACE_FIXES`, 7 entries): the 1988 labels of SAN ROQUE and SAN VICENTE (Northern Samar) and of ROXAS and SAN VICENTE (Palawan) are swapped. Ateneo's 1988 LAUR is LUPAO. Ateneo's 1995 BRAULIO E DUJALI is BABAK, since Braulio E. Dujali was only created in 1998. Marawi's 1995 officials were filed under Maguindanao.
  - **Old name attached:** BANNA ESPIRITU is BANNA (added to `TOWN_MAP`). This also changed 14 HF rows and 84 OpenHalalan rows.
- After the fixes, one flag remains, and it is expected: BABAK 1995 shares 4 surnames with Island Garden City of Samal 1998, because Babak merged into that city in 1998.
- Only 20 Ateneo rows now have a town that no other source confirms (SAN AGUSTIN and SULTAN SA MAROMATA, 1988).